backend/config/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_title = "EventMaster Admin"
admin.site.site_header = "EventMaster Admin"
admin.site.index_title = "EventMaster"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("event/", include("event.urls")),
    path('payments/', include('payments.urls')),
    path('payment/', include('payment.urls')),
    path("", include("home.urls"))
]

backend/event/urls.py
from django.urls import path

from event import views

app_name = "event"
urlpatterns = [
    path("", views.EventListView.as_view(), name="event_list"),
    path("<int:pk>", views.EventDetailView.as_view(), name="event_detail"),
    path("sign_up/<int:pk>", views.EventSignUpConfirmationView.as_view(),
         name="event_sign_up"),
    path("register/<int:pk>", views.RegistrationCreateView.as_view(),
         name="register"),
    path("register_success/<int:pk>",
         views.RegistrationSuccessfulView.as_view(), name="register_success"),
    path("register_failed", views.RegistrationFailedView.as_view(),
         name="register_failed"),
    path("register_payment_incomplete/<int:pk>",
         views.RegistrationPaymentIncompleteView.as_view(),
         name="register_payment_incomplete"),
    path("register_max_occupancy",
         views.RegistrationMaxOccupancyView.as_view(),
         name="register_max_occupancy"),
    path("user_events", views.UserEventsListView.as_view(),
         name="user_events_list")
]

backend/home/urls.py
from django.urls import path

from home import views


app_name = "home"
urlpatterns = [
    path("", views.AnnouncementListView.as_view(), name="home"),
]

backend/payment/urls.py
from django.urls import path

from payment import views

app_name = "payment"
urlpatterns = [
    path("create/<int:pk>", views.PaymentCreateView.as_view(), name="create"),
    path("<int:pk>", views.PaymentDetailView.as_view(), name="details"),
    path("wrong_user", views.PaymentWrongUser.as_view(), name="wrong_user"),
    path("success/<int:pk>", views.PaymentSuccess.as_view(), name="success"),
    path("failed/<int:pk>", views.PaymentFailed.as_view(), name="failed"),
]

backend/payment/models.py
from django.db import models

# Create your models here.
from decimal import Decimal

from django.urls import reverse
from payments import PurchasedItem
from payments.models import BasePayment

from config import settings


class Payment(BasePayment):

    def get_failure_url(self):
        return reverse("payment:failed", kwargs={'pk': self.pk})

    def get_success_url(self):
        return reverse("payment:success", kwargs={'pk': self.pk})

    registration = models.OneToOneField("event.Registration", on_delete=models.DO_NOTHING, null=True, blank=True)

    def get_purchased_items(self):
        return [PurchasedItem(name="Ticket",
                            quantity=1,
                            price=self.registration.event.price,
                            currency=self.currency,
                            sku='default',
                            tax_rate=Decimal(settings.PAYMENT_TICKET_TAX))]

backend/payment/views.py
import json
from decimal import Decimal

from django.contrib.auth import mixins
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views import generic
from payments import get_payment_model, RedirectNeeded
from payments.models import PaymentStatus

from config import settings
from payment.models import Payment
from event.models import Registration


class PaymentDetailView(mixins.LoginRequiredMixin, generic.DetailView):
    model = get_payment_model()

    # TODO: check permissions, only registration owner can see payment content

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['PaymentStatus'] = PaymentStatus
        context['redirect_url'] = json.loads(
            self.object.extra_data)['card_response']['redirectUri']
        return context


class PaymentCreateView(mixins.LoginRequiredMixin, generic.CreateView):
    model = get_payment_model()
    registration = None
    fields = ['billing_first_name', 'billing_last_name']

    def get(self, *args, **kwargs):
        registration = get_object_or_404(Registration, pk=self.kwargs["pk"])
        try:
            existing_payment = Payment.objects.get(registration_id=registration.id)
            return redirect(reverse('payment:details', kwargs={'pk': existing_payment.id}))
        except ObjectDoesNotExist:
            pass
        return super().get(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        registration = get_object_or_404(Registration, pk=self.kwargs["pk"])
        context["registration"] = registration
        return context

    def form_valid(self, form):
        registration = get_object_or_404(Registration, pk=self.kwargs["pk"])
        try:
            existing_payment = Payment.objects.get(registration_id=registration.id)
            return redirect(reverse('payment:details', kwargs={'pk': existing_payment.id}))
        except ObjectDoesNotExist:
            pass

        if registration.user.id != self.request.user.id:
            return redirect(reverse("payment:wrong_user"))
        form.instance.variant = "default"
        form.instance.description = f"Ticket for {registration.event.title}"
        form.instance.total = Decimal(registration.event.price)
        form.instance.tax = Decimal(
            registration.event.price * Decimal(settings.PAYMENT_TICKET_TAX))
        form.instance.currency = 'PLN'
        form.instance.delivery = Decimal(0)
        form.instance.billing_email = self.request.user.email
        form.instance.customer_ip_address = (self.request.META.get('HTTP_X_FORWARDED_FOR')
                                             or self.request.META.get('REMOTE_ADDR'))
        form.instance.registration = registration

        return super().form_valid(form)

    def get_success_url(self):
        self.object.save()
        try:
            self.object.get_form()
        except RedirectNeeded as redirect_to:
            return str(redirect_to)
        return reverse("payment:details", kwargs={"payment_id": self.object.pk})


class PaymentWrongUser(mixins.LoginRequiredMixin, generic.TemplateView):
    template_name = "payment/wrong_user.html"
    extra_context = {"message": "This registration is related to the other user.",
                     "title": "Payment Failed"}


class PaymentSuccess(mixins.LoginRequiredMixin, generic.DetailView):
    template_name = "payment/payment_success.html"
    model = get_payment_model()


class PaymentFailed(mixins.LoginRequiredMixin, generic.DetailView):
    template_name = "payment/payment_failed.html"
    model = get_payment_model()

backend/payment/templates/payment/payment_detail.html
{% extends 'base.html' %}

{% block title %}
    Payment Details
{% endblock title %}

{% block content %}
    <div class="card">
        <div class="card-header">
            Payment for registration for event
            <b>
                <a class="text-decoration-none"
                   href="{% url "event:event_detail" object.registration.event.id %}">
                    {{ object.registration.event.title }}
                </a>
            </b>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-5 col-md-3">Status: </div>
                <div class="col">{{ object.status }}</div>
            </div>
            <div class="row">
                <div class="col-5 col-md-3">Price : </div>
                <div class="col">{{ object.total }}{{ object.currency }}</div>
            </div>
            <div class="row">
                <div class="col-5 col-md-3">Customer first name: </div>
                <div class="col">{{ object.billing_first_name }}</div>
            </div>
            <div class="row">
                <div class="col-5 col-md-3">Customer second name: </div>
                <div class="col">{{ object.billing_second_name }}</div>
            </div>
            <div class="row">
                <div class="col-5 col-md-3">Customer email: </div>
                <div class="col">{{ object.billing_email }}</div>
            </div>
        </div>
        {% if object.status == PaymentStatus.WAITING %}
            <div class="card-footer">
                    <a class="btn btn-success" href="{{ redirect_url }}">Pay</a>
            </div>
        {% endif %}
    </div>
{% endblock content %}

backend/payment/templates/payment/payment_failed.html
{% extends 'base.html' %}

{% block title %}
    Payment failed
{% endblock title %}

{% block content %}
    <div class="card">
        <div class="card-body">
            {{ payment }}
            <h3>Payment failed</h3>
        </div>
    </div>
{% endblock content %}

backend/payment/templates/payment/payment_form.html
{% extends 'base.html' %}

{% block title %}
    Billing information for {{ registration.event.title }} ticket payment
{% endblock title %}

{% block content %}
    <div class="card">
    <div class="card-header">
        Billing information
    </div>
        <div class="card-body">
            <form action="{% url "payment:create" registration.id %}" method="POST" >
            {% csrf_token %}
            <div class="form-group row">
                <label for="billing_first_name" class=" col-4 col-md-2 col-form-label">First name: </label>
                <div class="col">
                    <input type="text" name="billing_first_name" class="form-control">
                </div>
            </div>
            <div class="form-group row mt-2">
                <label for="billing_last_name" class=" col-4 col-md-2 col-form-label">Last name: </label>
                <div class="col">
                    <input type="text" name="billing_last_name" class="form-control">
                </div>
            </div>
            <button type="submit" class="btn btn-success mx-auto mt-2">Pay</button>
        </form>
        </div>
    </div>
{% endblock content %}

backend/payment/templates/payment/payment_success.html
{% extends 'base.html' %}

{% block title %}
    Payment suceeded
{% endblock title %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <h3>Payment suceeded</h3>
        </div>
    </div>
{% endblock content %}

backend/payment/templates/payment/wrong_user.html
{% extends 'base.html' %}

{% block title %}
    Error - wrong user
{% endblock title %}

{% block content %}
  <div class="container" style="max-width: 40rem">
    <div class="card">
      <div class="card-body">
      <p>{{ message }}</p>
      <p>Please try again or get in touch with site administration.</p>
      <a type="submit" class="btn btn-success px-3"
         href="{% url 'home:home' %}">Home Page</a>
      </div>
    </div>
  </div>
{% endblock content %}