backend/config/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_title = "EventMaster Admin"
admin.site.site_header = "EventMaster Admin"
admin.site.index_title = "EventMaster"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("event/", include("event.urls")),
    path('payments/', include('payments.urls')),
    path('payment/', include('payment.urls')),
    path("", include("home.urls"))
]

backend/event/urls.py
from django.urls import path

from event import views

app_name = "event"
urlpatterns = [
    path("", views.EventListView.as_view(), name="event_list"),
    path("<int:pk>", views.EventDetailView.as_view(), name="event_detail"),
    path("sign_up/<int:pk>", views.EventSignUpConfirmationView.as_view(),
         name="event_sign_up"),
    path("register/<int:pk>", views.RegistrationCreateView.as_view(),
         name="register"),
    path("register_success/<int:pk>",
         views.RegistrationSuccessfulView.as_view(), name="register_success"),
    path("register_failed", views.RegistrationFailedView.as_view(),
         name="register_failed"),
    path("register_payment_incomplete/<int:pk>",
         views.RegistrationPaymentIncompleteView.as_view(),
         name="register_payment_incomplete"),
    path("register_max_occupancy",
         views.RegistrationMaxOccupancyView.as_view(),
         name="register_max_occupancy"),
    path("user_events", views.UserEventsListView.as_view(),
         name="user_events_list")
]

backend/home/urls.py
from django.urls import path

from home import views


app_name = "home"
urlpatterns = [
    path("", views.AnnouncementListView.as_view(), name="home"),
]

backend/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="{% static 'scripts/bootstrap.min.js' %}"></script>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
  <title>{% block title %}{% endblock title %}</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home:home' %}">EventMaster</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link" href="{% url 'home:home' %}">Home</a>
      </div>
      <div class="navbar-nav">
        <a class="nav-link" href="{% url 'event:event_list' %}">Events</a>
      </div>
      {% if user.is_authenticated %}
        <div class="navbar-nav">
          <a class="nav-link" href="{% url 'event:user_events_list' %}">
            My Events
          </a>
        </div>
      {% endif %}
      <div class="navbar-nav ms-auto">
        {% if user.is_superuser %}
          <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </div>
          <div class="navbar-nav">
        {% endif %}
        {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
        {% else %}
          <a class="nav-link" href="{% url 'account_login' %}">Login</a>
        {% endif %}
        </div>
    </div>
  </div>
</nav>

<div class="container">
  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <div class="alert alert-dismissible fade show
            alert-{% if message.tags %}{{ message.tags }}{% else %}info{% endif %}" role="alert">
          {{ message }}
        </div>
      {% endfor %}
    </ul>
  {% endif %}
  <div class="row justify-content-center">
    <div class="col-12 col-lg-8">
      {% block content %}{% endblock content %}
    </div>
  </div>

</div>

</body>
</html>