backend/config/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_title = "EventMaster Admin"
admin.site.site_header = "EventMaster Admin"
admin.site.index_title = "EventMaster"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("event/", include("event.urls")),
    path('payments/', include('payments.urls')),
    path('payment/', include('payment.urls')),
    path("", include("home.urls"))
]

backend/event/urls.py
from django.urls import path

from event import views

app_name = "event"
urlpatterns = [
    path("", views.EventListView.as_view(), name="event_list"),
    path("<int:pk>", views.EventDetailView.as_view(), name="event_detail"),
    path("sign_up/<int:pk>", views.EventSignUpConfirmationView.as_view(),
         name="event_sign_up"),
    path("register/<int:pk>", views.RegistrationCreateView.as_view(),
         name="register"),
    path("register_success/<int:pk>",
         views.RegistrationSuccessfulView.as_view(), name="register_success"),
    path("register_failed", views.RegistrationFailedView.as_view(),
         name="register_failed"),
    path("register_payment_incomplete/<int:pk>",
         views.RegistrationPaymentIncompleteView.as_view(),
         name="register_payment_incomplete"),
    path("register_max_occupancy",
         views.RegistrationMaxOccupancyView.as_view(),
         name="register_max_occupancy"),
    path("user_events", views.UserEventsListView.as_view(),
         name="user_events_list")
]

backend/home/urls.py
from django.urls import path

from home import views


app_name = "home"
urlpatterns = [
    path("", views.AnnouncementListView.as_view(), name="home"),
]

backend/event/models.py
from django.contrib.auth import get_user_model
from django.db import models

from event.helpers import user_event_deadline
from event.managers import EventRegistrationCountManager


class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=5000)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    registration_deadline = models.DateTimeField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    max_occupancy = models.IntegerField()
    location = models.CharField(max_length=50)

    creator = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING,
                                editable=False)
    creation_date = models.DateTimeField(auto_now=True, editable=False)

    # Custom managers
    objects = models.Manager()
    objects_with_registrations = EventRegistrationCountManager()

    def __str__(self):
        return f"{self.title}"


class Registration(models.Model):
    event = models.ForeignKey("Event", on_delete=models.DO_NOTHING)
    user = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING)
    payment_completed = models.BooleanField(default=False)
    payment_date = models.DateTimeField(blank=True, null=True)
    payment_deadline = models.DateTimeField(default=user_event_deadline)
    created = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING, null=True,
                                    editable=False, related_name='modified_by')

    def __str__(self):
        return f"{self.event.title} - {self.user}"

backend/event/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from event.models import Event


class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = ["title", "description", "start_time", "end_time",
                  "registration_deadline", "price", "max_occupancy",
                  "location"]

    def clean_price(self):
        price = self.cleaned_data["price"]
        if price < 0:
            raise ValidationError("Price cannot be negative.")
        return price

    def clean_max_occupancy(self):
        max_occupancy = self.cleaned_data["max_occupancy"]
        if max_occupancy < 0:
            raise ValidationError("Maximum occupancy cannot be negative.")
        if not isinstance(max_occupancy, int):
            raise ValidationError(
                "Maximum occupancy has to be an integer value.")
        return max_occupancy

    def clean_end_time(self):
        start_time = self.cleaned_data["start_time"]
        end_time = self.cleaned_data["end_time"]
        if start_time >= end_time:
            raise ValidationError("End time can't be lower than start time.")
        return end_time

    def clean_registration_deadline(self):
        start_time = self.cleaned_data["start_time"]
        registration_deadline = self.cleaned_data["registration_deadline"]
        if registration_deadline >= start_time:
            raise ValidationError(
                "Registration deadline can't be greater than start time.")
        return registration_deadline

backend/event/views.py
from decimal import Decimal

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import redirect
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from event.exceptions import PaymentIncompleteException
from event.models import Event, Registration

from payment.models import Payment

from config import settings


class EventListView(generic.ListView):
    model = Event
    context_object_name = "events"
    template_name = "event/event_list.html"
    queryset = Event.objects_with_registrations.all()


class EventDetailView(generic.DetailView):
    model = Event
    context_object_name = "event"

    def get_queryset(self, *args, **kwargs):
        return Event.objects_with_registrations.filter(pk=self.kwargs["pk"])


class EventSignUpConfirmationView(LoginRequiredMixin, generic.DetailView):
    model = Event
    context_object_name = "event"
    template_name = "event/event_confirmation.html"


class RegistrationCreateView(LoginRequiredMixin, generic.CreateView):
    model = Registration
    fields = []

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.free_event = False

    def form_valid(self, form):
        event = Event.objects_with_registrations.get(pk=self.kwargs["pk"])
        self.free_event = not bool(event.price)
        already_registered = Registration.objects.filter(
            event_id=self.kwargs["pk"], user_id=self.request.user.id)
        if already_registered:
            return redirect(reverse(
                "event:register_success", kwargs={"pk": self.kwargs["pk"]}))
        if event.seats_taken >= event.max_occupancy:
            return redirect(reverse("event:register_max_occupancy"))
        form.instance.event = event
        form.instance.user = self.request.user
        if self.free_event:
            form.instance.payment_completed = True
            form.instance.payment_date = timezone.now()
        return super().form_valid(form)

    def get_success_url(self):
        if self.free_event:
            return reverse("event:register_success",
                           kwargs={"pk": self.kwargs["pk"]})
        return reverse("payment:create", kwargs={"pk": self.object.id})


class RegistrationSuccessfulView(LoginRequiredMixin, generic.DetailView):
    context_object_name = "registration"
    template_name = "event/registration_successful.html"

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except PaymentIncompleteException as e:
            return redirect(reverse("event:register_payment_incomplete", kwargs={'pk': e.registration.id}))
        except Http404:
            return redirect(reverse("event:register_failed"))
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def get_object(self, queryset=None):
        event_pk = self.kwargs["pk"]
        user = self.request.user
        registrations = Registration.objects.select_related("event").filter(
            user_id=user.id, event_id=event_pk)
        if not registrations:
            raise Http404("No registration found!")
        try:
            registration = registrations.get(payment_completed=True)
        except Registration.DoesNotExist:
            raise PaymentIncompleteException(registration=registrations.get())
        return registration


class RegistrationFailedView(LoginRequiredMixin, generic.TemplateView):
    template_name = "event/registration_incomplete.html"
    extra_context = {"message": "Looks like something went wrong during "
                                "your registration attempt.",
                     "title": "Registration Failed"}


class RegistrationPaymentIncompleteView(LoginRequiredMixin,
                                        generic.DetailView):
    model = Registration
    context_object_name = "registration"
    template_name = "event/registration_incomplete.html"
    extra_context = {"message": "The payment have not been completed or is "
                                "still being processed.",
                     "title": "Payment Incomplete"}


class RegistrationMaxOccupancyView(LoginRequiredMixin, generic.TemplateView):
    template_name = "event/registration_incomplete.html"
    extra_context = {"message": "This event has already maximum occupancy.",
                     "title": "Registration Failed"}


class UserEventsListView(LoginRequiredMixin, generic.ListView):
    context_object_name = "registrations"
    template_name = "event/user_event_list.html"

    def get_queryset(self):
        return Registration.objects.select_related("event").filter(
            user_id=self.request.user.id, payment_completed=True).order_by(
            '-event__start_time')

backend/event/templates/event/event_confirmation.html
{% extends 'base.html' %}

{% block title %}
  {{ event.title }} Sign-up Confirmation
{% endblock title %}

{% block content %}
  <div class="container" style="max-width: 40rem">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ event.title }}</h5>
        <p>You are about to sign up for {{ event.title }}.<br> This event will
          take
          place {{ event.start_time|date:"d-m-Y" }}.
        </p>
        <div class="row pt-3 text-center">
          <div class="col-12 col-md-6 mb-2">
            <form method="POST" class="form-inline" style="width: 100%"
                  action="{%  url 'event:register' event.pk %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-success"
                      style="width: 100%">
                {% if event.price %}
                  Proceed to payment
                {% else %}
                  Register for free
                {% endif %}
              </button>
            </form>
          </div>
          <div class="col-12 col-md-6 mb-2">
            <a class="btn btn-secondary" style="width: 100%"
               href="{% url 'event:event_list' %}">
              Return
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

backend/event/templates/event/event_detail.html
{% extends 'base.html' %}

{% block title %}
  {{ event.title }} Details
{% endblock title %}

{% block content %}
  <div class="card">
    <div class="card-header p-4">
      <div class="row">
        <div class="col-sm-12 col-md-9 col-lg-10 me-auto">
          <h3>{{ event.title }}</h3>
        </div>
        <div
            class="d-block col-sm-6 col-md-3 col-lg-2 d-md-flex justify-content-end">
          <a class="btn btn-success mt-2 mt-md-0" style="max-height: 2.6rem"
             href="{% url 'event:event_sign_up' event.pk %}">Join Event</a>
        </div>
      </div>
    </div>
    {% with "30rem" as max_width %}
      <div class="card-body">
        <div class="row" style="max-width: {{ max_width }}">
          <div class="col"><h5>Start time</h5></div>
          <div class="col">{{ event.start_time|date:"h-m-Y H:i" }}</div>
        </div>
        <div class="row" style="max-width: {{ max_width }}">
          <div class="col"><h5>End time:</h5></div>
          <div class="col">{{ event.end_time|date:"h-m-Y H:i" }}</div>
        </div>
        <div class="row" style="max-width: {{ max_width }}">
          <div class="col"><h5>Seats taken:</h5></div>
          <div class="col">
            {{ event.seats_taken }}/{{ event.max_occupancy }}
          </div>
        </div>
        <div class="row" style="max-width: {{ max_width }}">
          <div class="col"><h5>Entrance Fee:</h5></div>
          <div class="col">{{ event.price }}</div>
        </div>
        <div class="row" style="max-width: {{ max_width }}">
          <div class="col"><h5>Registration deadline:</h5></div>
          <div class="col">
            {{ event.registration_deadline|date:"h-m-Y H:i" }}</div>
        </div>
        <div class="row" style="max-width: {{ max_width }}">
          <div class="col"><h5>Location:</h5></div>
          <div class="col">{{ event.location }}</div>
        </div>
        <hr>
        <p>{{ event.description }}</p>
      </div>
    {% endwith %}
  </div>
{% endblock content %}

backend/event/templates/event/event_list.html
{% extends 'base.html' %}

{% block title %}
  Event List
{% endblock title %}

{% block content %}
  {% for event in events %}
    <div class="card mb-4">
      <div class="card-header p-4">
        <div class="row">
          <div class="col-sm-12 col-md-9 col-lg-10 me-auto">
            <h3>
              <a href="{% url 'event:event_detail' event.pk %}"
                 class="link-dark">{{ event.title }}</a>
            </h3>
          </div>
          <div
              class="d-block col-sm-6 col-md-3 col-lg-2 d-md-flex justify-content-end">
            <a class="btn btn-success mt-2 mt-md-0"
               style="max-height: 2.6rem"
               href="{% url 'event:event_sign_up' event.pk %}">Join Event</a>
          </div>
        </div>
      </div>
      <div class="card-body">
        <div class="row" style="max-width: 20rem">
          <div class="col"><h5>Start time</h5></div>
          <div class="col">{{ event.start_time|date:"d-m-Y H:i" }}</div>
        </div>
        <div class="row" style="max-width: 20rem">
          <div class="col"><h5>Seats Taken:</h5></div>
          <div class="col">{{ event.seats_taken }}/{{ event.max_occupancy }}</div>
        </div>
        {% if event.price > 0 %}
            <div class="row" style="max-width: 20rem">
                  <div class="col"><h5>Price:</h5></div>
                  <div class="col">{{ event.price }}PLN</div>
            </div>
        {% endif %}
        <hr>
        <p>{{ event.description }}</p>
      </div>
    </div>
    {% empty %}
    <h1>No Upcoming Events</h1>
  {% endfor %}
{% endblock content %}

backend/event/templates/event/registration_failed.html
{% extends 'base.html' %}

{% block title %}
  Registration attempt failed
{% endblock title %}

{% block content %}
  <div class="card my-3 text-center">
    <div class="card-header">
      <h3 class="text-danger">Registration Failed</h3>
    </div>
    <div class="card-body">
      <p>Looks like something went wrong during your registration attempt.</p>
      <p>Please try again or get in touch with site administration.</p>
      <a type="submit" class="btn btn-success px-3"
         href="{% url 'home:home' %}">Home Page</a>
    </div>
  </div>
{% endblock content %}

backend/event/templates/event/registration_incomplete.html
{% extends 'base.html' %}

{% block title %}
  {{ title }}
{% endblock title %}

{% block content %}
  <div class="card my-3 text-center">
    <div class="card-header">
      <h3 class="text-danger">{{ title }}</h3>
    </div>
    <div class="card-body">
      <p>{{ message }}</p>
      <p>Please try again or get in touch with site administration.</p>
      <a type="submit" class="btn btn-success px-3"
         href="{% url 'home:home' %}">Home Page</a>
    </div>
  </div>
{% endblock content %}

backend/event/templates/event/registration_successful.html
{% extends 'base.html' %}

{% block title %}
  Registration successful
{% endblock title %}

{% block content %}
  <div class="card">
    <div class="card-header text-center">
      <h3>Registration Completed</h3>
    </div>
    <div class="card-body text-center">
      <p>Your registration for
        <a class="link-dark"
           href="{% url 'event:event_detail' registration.event.pk %}">
          <strong>{{ registration.event.title }}</strong>
        </a>was completed successfully.</p>
      <p>This event is scheduled to be held in
        <strong>{{ registration.event.location }}</strong> on <strong>
          {{ registration.event.start_time|date:"d.m.Y" }}</strong> starting
        from <strong>{{ registration.event.start_time|date:"H:i" }}</strong>.
      </p>
      <a type="submit" class="btn btn-success px-3"
         href="{% url 'home:home' %}">Home Page</a>
    </div>
  </div>
{% endblock content %}

backend/event/templates/event/user_event_list.html
{% extends 'base.html' %}

{% block title %}
  User Events List
{% endblock title %}

{% block content %}
  {% for registration in registrations %}
    <div class="card mb-4">
      <div class="card-header p-4">
        <h3>
          <a rel="stylesheet" class="link-dark "
             href="{% url 'event:event_detail' registration.event.pk %}">
            {{ registration.event.title }}
          </a>
        </h3>
      </div>
      <div class="card-body">
        <div class="row" style="max-width: {{ max_width }}">
          <div class="col"><h5>Start time</h5></div>
          <div class="col">
            {{ registration.event.start_time|date:"d-m-Y H:i" }}
          </div>
        </div>
        <div class="row" style="max-width: {{ max_width }}">
          <div class="col"><h5>End time:</h5></div>
          <div class="col">
            {{ registration.event.end_time|date:"d-m-Y H:i" }}</div>
        </div>
        <div class="row" style="max-width: {{ max_width }}">
          <div class="col"><h5>Location:</h5></div>
          <div class="col">{{ registration.event.location }}</div>
        </div>
        <hr>
        <p>{{ registration.event.description }}</p>
      </div>
    </div>
    {% empty %}
    <h1>You have not signed up for any event.</h1>
  {% endfor %}
{% endblock content %}